import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def plot_comparison(
    csv_path: Path,
    out_png: Path,
    sort_by: str = "test_macro_f1_calibrated",
    title: str = "Label Source Comparison (Calibrated F1)",
) -> None:
    if not csv_path.exists():
        raise FileNotFoundError(f"Comparison CSV not found: {csv_path}")

    df = pd.read_csv(csv_path)
    required = {
        "label_source",
        "test_macro_f1_calibrated",
        "test_micro_f1_calibrated",
    }
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"CSV missing required columns: {sorted(missing)}")

    if sort_by not in df.columns:
        raise ValueError(f"sort_by column '{sort_by}' not found in CSV")

    df_plot = df.sort_values(sort_by, ascending=False).reset_index(drop=True)

    x = range(len(df_plot))
    width = 0.36

    plt.figure(figsize=(10, 5.5))
    plt.bar([i - width / 2 for i in x], df_plot["test_macro_f1_calibrated"], width=width, label="Macro F1 (cal)")
    plt.bar([i + width / 2 for i in x], df_plot["test_micro_f1_calibrated"], width=width, label="Micro F1 (cal)")

    plt.xticks(list(x), df_plot["label_source"].astype(str).tolist())
    plt.ylim(0.0, 1.0)
    plt.ylabel("F1 score")
    plt.title(title)
    plt.legend()
    plt.grid(axis="y", alpha=0.25)

    # annotate bars with compact values
    for i, (_, row) in enumerate(df_plot.iterrows()):
        plt.text(i - width / 2, row["test_macro_f1_calibrated"] + 0.01, f"{row['test_macro_f1_calibrated']:.3f}", ha="center", va="bottom", fontsize=9)
        plt.text(i + width / 2, row["test_micro_f1_calibrated"] + 0.01, f"{row['test_micro_f1_calibrated']:.3f}", ha="center", va="bottom", fontsize=9)

    out_png.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(out_png, dpi=170)
    plt.close()

    print(f"Saved plot: {out_png}")
    print("\nLeaderboard preview:")
    cols = [
        "label_source",
        "test_macro_f1_calibrated",
        "test_micro_f1_calibrated",
        "n_rows",
        "n_classes",
    ]
    print(df_plot[[c for c in cols if c in df_plot.columns]].to_string(index=False))


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot label-source comparison from CSV output")
    parser.add_argument(
        "--csv",
        default="training/models/label_source_comparison.csv",
        help="Path to comparison CSV generated by compare_multilabel_label_sources.py",
    )
    parser.add_argument(
        "--out",
        default="training/models/label_source_comparison.png",
        help="Output PNG path",
    )
    parser.add_argument(
        "--sort_by",
        default="test_macro_f1_calibrated",
        help="Column to sort by before plotting",
    )
    parser.add_argument(
        "--title",
        default="Label Source Comparison (Calibrated F1)",
        help="Plot title",
    )
    args = parser.parse_args()

    plot_comparison(
        csv_path=Path(args.csv),
        out_png=Path(args.out),
        sort_by=args.sort_by,
        title=args.title,
    )


if __name__ == "__main__":
    main()
